import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, Bell, CalendarDays, ChevronDown, Clock3, FileText, LayoutDashboard, Mail, Menu, Plus, Search, Settings, ShieldCheck, Sparkles, Stethoscope, Users, X } from 'lucide-react';
import './styles.css';

const doctors = [
  { id: 1, name: 'Dr. Maya Patel', specialty: 'Family medicine', initials: 'MP', color: 'coral', next: 'Today, 2:30 PM', patients: 18, status: 'In clinic' },
  { id: 2, name: 'Dr. Elias Chen', specialty: 'Cardiology', initials: 'EC', color: 'blue', next: 'Tomorrow, 9:00 AM', patients: 12, status: 'Available' },
  { id: 3, name: 'Dr. Sofia Alvarez', specialty: 'Dermatology', initials: 'SA', color: 'yellow', next: 'Wed, 11:15 AM', patients: 9, status: 'Away' }
];
const initialAppointments = [
  { id: 1, patient: 'Amelia Rodriguez', initials: 'AR', doctor: 'Dr. Maya Patel', type: 'Follow-up', date: 'Today', time: '2:30 PM', status: 'Confirmed', risk: 'Low', color: 'coral' },
  { id: 2, patient: 'Noah Williams', initials: 'NW', doctor: 'Dr. Elias Chen', type: 'New patient', date: 'Today', time: '3:15 PM', status: 'Needs review', risk: 'Medium', color: 'blue' },
  { id: 3, patient: 'Liam Thompson', initials: 'LT', doctor: 'Dr. Maya Patel', type: 'Annual physical', date: 'Tomorrow', time: '9:00 AM', status: 'Confirmed', risk: 'Low', color: 'yellow' },
  { id: 4, patient: 'Sophia Kim', initials: 'SK', doctor: 'Dr. Sofia Alvarez', type: 'Consultation', date: 'Tomorrow', time: '11:15 AM', status: 'Awaiting form', risk: 'Low', color: 'lavender' }
];

function App() {
  const [role, setRole] = useState('Patient');
  const [view, setView] = useState('Overview');
  const [appointments, setAppointments] = useState(initialAppointments);
  const [showBooking, setShowBooking] = useState(false);
  const [toast, setToast] = useState('');
  const [query, setQuery] = useState('');
  const nav = role === 'Admin' ? ['Overview', 'Doctors', 'Patients', 'Settings'] : role === 'Doctor' ? ['Overview', 'My patients', 'Calendar', 'Notes'] : ['Overview', 'Find a doctor', 'My appointments', 'Health records'];
  const visibleAppointments = appointments.filter(a => !query || `${a.patient} ${a.doctor} ${a.type}`.toLowerCase().includes(query.toLowerCase()));
  const notify = (message) => { setToast(message); window.setTimeout(() => setToast(''), 3500); };
  const book = (doctor, time) => {
    setAppointments(current => [{ id: Date.now(), patient: 'You', initials: 'YO', doctor: doctor.name, type: 'New consultation', date: 'Thu, Aug 28', time, status: 'Confirmed', risk: 'Pending', color: doctor.color }, ...current]);
    setShowBooking(false); notify(`Appointment held with ${doctor.name}. Confirmation sent.`);
  };
  return <div className="app-shell">
    <aside className="sidebar">
      <div className="brand"><div className="brand-mark"><Activity size={19} /></div><span>carepath</span></div>
      <div className="workspace-switcher"><div className="tiny-label">WORKSPACE</div><button className="workspace-button"><span>Riverside Clinic</span><ChevronDown size={15} /></button></div>
      <nav>{nav.map(item => <button key={item} className={`nav-item ${view === item ? 'active' : ''}`} onClick={() => setView(item)}>{item === 'Overview' ? <LayoutDashboard size={18}/> : item === 'Find a doctor' || item === 'Doctors' ? <Stethoscope size={18}/> : item === 'My patients' || item === 'Patients' ? <Users size={18}/> : item === 'Calendar' || item === 'My appointments' ? <CalendarDays size={18}/> : item === 'Notes' || item === 'Health records' ? <FileText size={18}/> : <Settings size={18}/>}<span>{item}</span>{item === 'My appointments' && <span className="nav-count">3</span>}</button>)}</nav>
      <div className="sidebar-bottom"><div className="support-card"><div className="support-icon"><ShieldCheck size={17}/></div><strong>Care team support</strong><span>We usually reply in under 10 min.</span><button onClick={() => notify('Support request started.')}>Message team <span>↗</span></button></div><div className="user-row"><div className="avatar coral">JD</div><div><strong>Jordan Davis</strong><span>{role} account</span></div><ChevronDown size={15}/></div></div>
    </aside>
    <main className="main-content">
      <header className="topbar"><button className="mobile-menu"><Menu size={20}/></button><div className="breadcrumb"><span>Workspace</span><b>/</b><strong>{view}</strong></div><div className="top-actions"><button className="icon-button" aria-label="Notifications" onClick={() => notify('You have 2 new notifications.')}><Bell size={19}/><i></i></button><div className="role-toggle"><span>View as</span><select value={role} onChange={e => { setRole(e.target.value); setView('Overview'); }}><option>Patient</option><option>Doctor</option><option>Admin</option></select></div><div className="avatar coral">JD</div></div></header>
      <div className="page-wrap">
        <section className="page-heading"><div><p className="eyebrow">Thursday, August 21, 2025</p><h1>{role === 'Patient' ? 'Good morning, Jordan' : role === 'Doctor' ? 'Good morning, Dr. Patel' : 'Good morning, Jordan'}</h1><p className="subtitle">{role === 'Patient' ? 'Your care, coordinated in one calm place.' : role === 'Doctor' ? 'Here is what needs your attention today.' : 'A clear view of the clinic, at a glance.'}</p></div><button className="primary-button" onClick={() => setShowBooking(true)}><Plus size={18}/> Book appointment</button></section>
        {role === 'Patient' ? <PatientView appointments={visibleAppointments} onBook={() => setShowBooking(true)} notify={notify}/> : role === 'Doctor' ? <DoctorView appointments={visibleAppointments} notify={notify}/> : <AdminView doctors={doctors} appointments={appointments} notify={notify}/>} 
      </div>
    </main>
    {showBooking && <BookingModal onClose={() => setShowBooking(false)} onBook={book}/>} 
    {toast && <div className="toast"><Sparkles size={16}/>{toast}</div>}
  </div>;
}

function PatientView({ appointments, onBook, notify }) { return <>
  <div className="patient-hero"><div><span className="status-pill green"><span className="dot"></span> Care plan on track</span><h2>Next up: your visit with<br/><em>Dr. Maya Patel</em></h2><div className="visit-meta"><span><CalendarDays size={16}/> Today, Aug 21</span><span><Clock3 size={16}/> 2:30 PM</span><span className="video-tag">In person</span></div><button className="text-button" onClick={() => notify('Appointment details opened.')}>View appointment details <span>→</span></button></div><div className="hero-illustration"><div className="sun"></div><div className="leaf leaf-one"></div><div className="leaf leaf-two"></div><div className="paper"><CalendarDays size={35}/><span>2:30</span></div></div></div>
  <div className="section-head"><div><h2>Prepare for your visit</h2><p>Small steps that make your time count.</p></div><span className="progress-label">2 of 3 complete</span></div><div className="prep-grid"><PrepCard icon={<FileText/>} title="Symptom form" text="Help your doctor come prepared." state="Complete" done/><PrepCard icon={<Mail/>} title="Visit reminders" text="Email and calendar alerts are on." state="Active"/><PrepCard icon={<ShieldCheck/>} title="Insurance details" text="Add your coverage information." state="Add details" action={onBook}/></div>
  <div className="section-head appointments-head"><div><h2>Upcoming appointments</h2><p>Everything on your care calendar.</p></div><button className="ghost-button" onClick={onBook}>See all appointments <span>→</span></button></div><AppointmentTable appointments={appointments} notify={notify}/>
</> }
function PrepCard({icon,title,text,state,done,action}) { return <div className="prep-card"><div className="prep-icon">{icon}</div><div className="prep-copy"><h3>{title}</h3><p>{text}</p></div><button className={done ? 'complete' : 'prep-action'} onClick={action}>{done ? '✓ ' : ''}{state}</button></div> }
function DoctorView({ appointments, notify }) { return <><div className="metrics"><Metric label="Today's visits" value="8" detail="2 forms to review"/><Metric label="Unread summaries" value="3" detail="Needs your attention" alert/><Metric label="This week" value="26" detail="4.2 avg. visits/day"/><Metric label="Completion rate" value="94%" detail="↑ 6% from last month"/></div><div className="section-head appointments-head"><div><h2>Today’s schedule</h2><p>AI summaries are ready before each visit.</p></div><div className="search-box"><Search size={16}/><input placeholder="Search patients" onChange={e => {}}/></div></div><AppointmentTable appointments={appointments} doctor notify={notify}/><div className="ai-banner"><div className="ai-orb"><Sparkles size={20}/></div><div><strong>Three pre-visit summaries are ready</strong><p>Review symptoms and suggested questions before your next consultation.</p></div><button className="ghost-button" onClick={() => notify('Opening summary review queue.')}>Review queue <span>→</span></button></div></> }
function AdminView({doctors, appointments, notify}) { return <><div className="metrics"><Metric label="Appointments today" value="24" detail="↑ 12% from last Thursday"/><Metric label="Active doctors" value="12" detail="2 on leave this week"/><Metric label="Open slots" value="38" detail="Across 4 specialisations"/><Metric label="Notification health" value="99.2%" detail="All systems operational"/></div><div className="section-head appointments-head"><div><h2>Clinic pulse</h2><p>Manage people, availability, and care operations.</p></div><button className="primary-button small" onClick={() => notify('Doctor profile flow opened.')}> <Plus size={16}/> Add doctor</button></div><div className="admin-grid"><div className="panel"><div className="panel-title"><h3>Doctor availability</h3><button className="ghost-button">Manage <span>→</span></button></div>{doctors.map(d => <div className="doctor-row" key={d.id}><div className={`avatar ${d.color}`}>{d.initials}</div><div className="doctor-info"><strong>{d.name}</strong><span>{d.specialty} · {d.patients} visits today</span></div><span className={`availability ${d.status === 'Away' ? 'away' : ''}`}><i></i>{d.status}</span><button className="more-button" onClick={() => notify(`${d.name}'s profile opened.`)}>•••</button></div>)}</div><div className="panel activity-panel"><div className="panel-title"><h3>Recent activity</h3><button className="more-button">•••</button></div><ActivityItem icon={<CalendarDays/>} text="Appointment confirmed" sub="Amelia Rodriguez · 2 min ago"/><ActivityItem icon={<Bell/>} text="Leave conflict resolved" sub="Dr. Chen · Aug 23 · 4 patients notified"/><ActivityItem icon={<Mail/>} text="Reminder batch delivered" sub="18 medication reminders · 8 min ago"/></div></div></> }
function ActivityItem({icon,text,sub}) { return <div className="activity-item"><div className="activity-icon">{icon}</div><div><strong>{text}</strong><span>{sub}</span></div></div> }
function Metric({label,value,detail,alert}) { return <div className="metric"><span>{label}</span><strong className={alert ? 'alert-number' : ''}>{value}</strong><small>{detail}</small></div> }
function AppointmentTable({appointments,doctor,notify}) { return <div className="table-wrap"><table><thead><tr><th>Patient</th><th>{doctor ? 'Visit type' : 'Provider'}</th><th>Date & time</th><th>Status</th><th></th></tr></thead><tbody>{appointments.slice(0,5).map(a => <tr key={a.id}><td><div className="table-person"><div className={`avatar small ${a.color}`}>{a.initials}</div><div><strong>{a.patient}</strong><span>{a.type}</span></div></div></td><td>{doctor ? a.type : a.doctor}</td><td><strong>{a.date}</strong><span className="table-time">{a.time}</span></td><td><span className={`table-status ${a.status === 'Needs review' ? 'review' : a.status === 'Awaiting form' ? 'awaiting' : ''}`}><i></i>{a.status}</span></td><td><button className="more-button" onClick={() => notify(`Details for ${a.patient} opened.`)}>•••</button></td></tr>)}</tbody></table></div> }
function BookingModal({onClose,onBook}) { const [selected,setSelected]=useState(doctors[0]); const [symptoms,setSymptoms]=useState(''); return <div className="modal-backdrop"><div className="modal"><button className="close-button" onClick={onClose}><X size={19}/></button><p className="eyebrow">NEW APPOINTMENT</p><h2>Find the right care</h2><p className="modal-subtitle">Share a little context so your care team can prepare.</p><label>Specialisation<select value={selected.id} onChange={e => setSelected(doctors.find(d => d.id === Number(e.target.value)))}>{doctors.map(d => <option key={d.id} value={d.id}>{d.specialty}</option>)}</select></label><div className="selected-doctor"><div className={`avatar ${selected.color}`}>{selected.initials}</div><div><strong>{selected.name}</strong><span>{selected.specialty}</span></div><span className="availability"><i></i>Available</span></div><label>What brings you in? <span className="optional">Optional</span><textarea value={symptoms} onChange={e => setSymptoms(e.target.value)} placeholder="Tell us about your symptoms or questions..." /></label><div className="slot-label">Choose a time</div><div className="slots"><button className="slot active">Thu 28 · 9:00 AM</button><button className="slot">Thu 28 · 10:30 AM</button><button className="slot">Fri 29 · 2:00 PM</button></div><button className="primary-button full" onClick={() => onBook(selected, '9:00 AM')}>Confirm appointment <span>→</span></button><p className="modal-footnote"><ShieldCheck size={14}/> Your details are private and encrypted.</p></div></div> }

createRoot(document.getElementById('root')).render(<App />);
